ARG GO_VERSION=1.26.5
FROM golang:${GO_VERSION}-bookworm AS builder

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY operator ./operator
RUN CGO_ENABLED=0 go build -trimpath -ldflags='-s -w' -o /out/epoch-operator ./operator/cmd/epoch-operator

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=builder /out/epoch-operator /usr/local/bin/epoch-operator
USER 65532:65532
ENTRYPOINT ["/usr/local/bin/epoch-operator"]
