// Code generated by controller-gen conventions; maintained with the API until generation is automated. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *EpochCluster) DeepCopyInto(out *EpochCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.deepCopyInto(&out.Spec)
	if in.Status.Backup.LastSuccessfulTime != nil {
		value := in.Status.Backup.LastSuccessfulTime.DeepCopy()
		out.Status.Backup.LastSuccessfulTime = value
	}
	if in.Status.Backup.LastFailureTime != nil {
		value := in.Status.Backup.LastFailureTime.DeepCopy()
		out.Status.Backup.LastFailureTime = value
	}
	if in.Status.Upgrade.TargetOrdinal != nil {
		value := *in.Status.Upgrade.TargetOrdinal
		out.Status.Upgrade.TargetOrdinal = &value
	}
	if in.Status.Upgrade.StartedAt != nil {
		out.Status.Upgrade.StartedAt = in.Status.Upgrade.StartedAt.DeepCopy()
	}
	if in.Status.Upgrade.StepStartedAt != nil {
		out.Status.Upgrade.StepStartedAt = in.Status.Upgrade.StepStartedAt.DeepCopy()
	}
	if in.Status.Conditions != nil {
		out.Status.Conditions = make([]metav1.Condition, len(in.Status.Conditions))
		copy(out.Status.Conditions, in.Status.Conditions)
	}
}

func (in *EpochCluster) DeepCopy() *EpochCluster {
	if in == nil {
		return nil
	}
	out := new(EpochCluster)
	in.DeepCopyInto(out)
	return out
}

func (in *EpochCluster) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *EpochClusterList) DeepCopyInto(out *EpochClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]EpochCluster, len(in.Items))
		for index := range in.Items {
			in.Items[index].DeepCopyInto(&out.Items[index])
		}
	}
}

func (in *EpochClusterList) DeepCopy() *EpochClusterList {
	if in == nil {
		return nil
	}
	out := new(EpochClusterList)
	in.DeepCopyInto(out)
	return out
}

func (in *EpochClusterList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *EpochClusterSpec) deepCopyInto(out *EpochClusterSpec) {
	*out = *in
	if in.StorageClassName != nil {
		value := *in.StorageClassName
		out.StorageClassName = &value
	}
	if in.Restore != nil {
		out.Restore = &RestoreSpec{ObjectName: in.Restore.ObjectName, EncryptionSecret: in.Restore.EncryptionSecret}
	}
	if in.Upgrade.RollbackOnFailure != nil {
		value := *in.Upgrade.RollbackOnFailure
		out.Upgrade.RollbackOnFailure = &value
	}
	out.AllowedOrigins = append([]string(nil), in.AllowedOrigins...)
	in.NodeResources.DeepCopyInto(&out.NodeResources)
	in.ControlResources.DeepCopyInto(&out.ControlResources)
	if in.NodeSelector != nil {
		out.NodeSelector = make(map[string]string, len(in.NodeSelector))
		for key, value := range in.NodeSelector {
			out.NodeSelector[key] = value
		}
	}
	if in.Tolerations != nil {
		out.Tolerations = make([]corev1.Toleration, len(in.Tolerations))
		for index := range in.Tolerations {
			in.Tolerations[index].DeepCopyInto(&out.Tolerations[index])
		}
	}
	if in.Affinity != nil {
		out.Affinity = in.Affinity.DeepCopy()
	}
}
