"""Regenerate namespaced Python management messages and typed gRPC bindings.

Generated imports/module identities are mechanically namespaced, and bare
constructor Mapping annotations receive explicit string/object parameters. The
protobuf descriptors and wire package/method identities are never changed.
"""

from __future__ import annotations

import argparse
import importlib.metadata
import subprocess
import sys
import tempfile
from pathlib import Path

from google.protobuf import descriptor_pb2

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "spec/proto"
OUTPUT = ROOT / "sdk/python/src/epoch_sdk/_generated"
NAMESPACE = "epoch_sdk._generated."
PINNED = {"grpcio-tools": "1.84.0", "grpcio": "1.84.0", "protobuf": "7.35.1"}


def generate() -> dict[Path, str]:
    for package, required in PINNED.items():
        if importlib.metadata.version(package) != required:
            raise SystemExit(f"generation requires {package}=={required}")
    with tempfile.TemporaryDirectory(prefix="epoch-python-generate-") as directory:
        temporary = Path(directory)
        descriptors = temporary / "contract.pb"
        subprocess.run(
            [
                sys.executable,
                "-m",
                "grpc_tools.protoc",
                f"-I{SOURCE}",
                f"--python_out={temporary}",
                f"--pyi_out={temporary}",
                f"--grpc_python_out={temporary}",
                f"--descriptor_set_out={descriptors}",
                "epoch/v1/common.proto",
                "epoch/v1/regional_admin.proto",
            ],
            check=True,
        )
        files: dict[Path, str] = {}
        for filename in (
            "common_pb2.py",
            "common_pb2.pyi",
            "regional_admin_pb2.py",
            "regional_admin_pb2.pyi",
            "regional_admin_pb2_grpc.py",
        ):
            path = Path("epoch/v1") / filename
            content = (temporary / path).read_text()
            content = content.replace(
                "from epoch.v1 import ", f"from {NAMESPACE}epoch.v1 import "
            )
            for module in ("common_pb2", "regional_admin_pb2"):
                content = content.replace(
                    f"'epoch.v1.{module}'", f"'{NAMESPACE}epoch.v1.{module}'"
                )
            if path.suffix == ".pyi":
                content = content.replace(", _Mapping]", ", _Mapping[str, object]]")
            files[path] = content
        contract = descriptor_pb2.FileDescriptorSet.FromString(descriptors.read_bytes())
        api = next(
            file for file in contract.file if file.name.endswith("regional_admin.proto")
        )
        service = api.service[0]
        lines = [
            "# Generated by scripts/generate-python-management.py. DO NOT EDIT.",
            "from collections.abc import Iterator",
            "import grpc",
            "from . import regional_admin_pb2 as messages",
            "",
            f"class {service.name}Stub:",
            "    def __init__(self, channel: grpc.Channel) -> None: ...",
        ]
        for method in service.method:
            if method.client_streaming:
                raise SystemExit(
                    "review Python streaming generation before extending this contract"
                )
            request, response = (
                method.input_type.split(".")[-1],
                method.output_type.split(".")[-1],
            )
            callable_type = (
                "UnaryStreamMultiCallable"
                if method.server_streaming
                else "UnaryUnaryMultiCallable"
            )
            lines.append(
                f"    {method.name}: grpc.{callable_type}[messages.{request}, messages.{response}]"
            )
        lines += ["", f"class {service.name}Servicer:"]
        for method in service.method:
            request, response = (
                method.input_type.split(".")[-1],
                method.output_type.split(".")[-1],
            )
            result = (
                f"Iterator[messages.{response}]"
                if method.server_streaming
                else f"messages.{response}"
            )
            lines.append(
                f"    def {method.name}(self, request: messages.{request}, "
                f"context: grpc.ServicerContext) -> {result}: ..."
            )
        lines += [
            "",
            f"def add_{service.name}Servicer_to_server(servicer: {service.name}Servicer, "
            "server: grpc.Server) -> None: ...",
            "",
        ]
        files[Path("epoch/v1/regional_admin_pb2_grpc.pyi")] = "\n".join(lines)
        for package in (Path("."), Path("epoch"), Path("epoch/v1")):
            files[package / "__init__.py"] = ""
        return files


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = generate()
    actual = {
        path.relative_to(OUTPUT)
        for path in OUTPUT.rglob("*")
        if path.is_file() and path.suffix in (".py", ".pyi")
    }
    unexpected = sorted(actual - generated.keys())
    if unexpected:
        raise SystemExit(
            "unexpected Python generated source: " + ", ".join(map(str, unexpected))
        )
    stale = []
    for path, content in generated.items():
        destination = OUTPUT / path
        if args.check:
            if not destination.exists() or destination.read_text() != content:
                stale.append(str(destination.relative_to(ROOT)))
        else:
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(content)
    if stale:
        raise SystemExit("stale Python management bindings: " + ", ".join(stale))
    print(
        "Python management bindings match the pinned contract"
        if args.check
        else "generated Python management bindings"
    )


if __name__ == "__main__":
    main()
