# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from epoch_sdk._generated.epoch.v1 import regional_admin_pb2 as epoch_dot_v1_dot_regional__admin__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in epoch/v1/regional_admin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RegionalAdminServiceStub:
    """RegionalAdmin is the versioned boundary between managed Go reconciliation
    and a regional Rust control surface. It carries desired metadata only.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ApplyResource = channel.unary_unary(
                '/epoch.v1.RegionalAdminService/ApplyResource',
                request_serializer=epoch_dot_v1_dot_regional__admin__pb2.ApplyResourceRequest.SerializeToString,
                response_deserializer=epoch_dot_v1_dot_regional__admin__pb2.ApplyResourceResponse.FromString,
                _registered_method=True)
        self.GetResource = channel.unary_unary(
                '/epoch.v1.RegionalAdminService/GetResource',
                request_serializer=epoch_dot_v1_dot_regional__admin__pb2.GetResourceRequest.SerializeToString,
                response_deserializer=epoch_dot_v1_dot_regional__admin__pb2.GetResourceResponse.FromString,
                _registered_method=True)
        self.ListResources = channel.unary_unary(
                '/epoch.v1.RegionalAdminService/ListResources',
                request_serializer=epoch_dot_v1_dot_regional__admin__pb2.ListResourcesRequest.SerializeToString,
                response_deserializer=epoch_dot_v1_dot_regional__admin__pb2.ListResourcesResponse.FromString,
                _registered_method=True)
        self.DeleteResource = channel.unary_unary(
                '/epoch.v1.RegionalAdminService/DeleteResource',
                request_serializer=epoch_dot_v1_dot_regional__admin__pb2.DeleteResourceRequest.SerializeToString,
                response_deserializer=epoch_dot_v1_dot_regional__admin__pb2.DeleteResourceResponse.FromString,
                _registered_method=True)
        self.BatchApplyResources = channel.unary_unary(
                '/epoch.v1.RegionalAdminService/BatchApplyResources',
                request_serializer=epoch_dot_v1_dot_regional__admin__pb2.BatchApplyResourcesRequest.SerializeToString,
                response_deserializer=epoch_dot_v1_dot_regional__admin__pb2.BatchApplyResourcesResponse.FromString,
                _registered_method=True)
        self.GetOperation = channel.unary_unary(
                '/epoch.v1.RegionalAdminService/GetOperation',
                request_serializer=epoch_dot_v1_dot_regional__admin__pb2.GetOperationRequest.SerializeToString,
                response_deserializer=epoch_dot_v1_dot_regional__admin__pb2.GetOperationResponse.FromString,
                _registered_method=True)
        self.WatchResourceChanges = channel.unary_stream(
                '/epoch.v1.RegionalAdminService/WatchResourceChanges',
                request_serializer=epoch_dot_v1_dot_regional__admin__pb2.WatchResourceChangesRequest.SerializeToString,
                response_deserializer=epoch_dot_v1_dot_regional__admin__pb2.WatchResourceChangesResponse.FromString,
                _registered_method=True)


class RegionalAdminServiceServicer:
    """RegionalAdmin is the versioned boundary between managed Go reconciliation
    and a regional Rust control surface. It carries desired metadata only.
    """

    def ApplyResource(self, request, context):
        """ApplyResource idempotently creates or updates desired resource state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResource(self, request, context):
        """GetResource returns one resource by fully qualified name.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListResources(self, request, context):
        """ListResources returns a stable page of resources.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteResource(self, request, context):
        """DeleteResource removes desired resource state idempotently.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchApplyResources(self, request, context):
        """BatchApplyResources atomically commits 1-128 desired resource changes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOperation(self, request, context):
        """GetOperation returns one durable request-token outcome.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchResourceChanges(self, request, context):
        """WatchResourceChanges streams resumable, bounded change checkpoints.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegionalAdminServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ApplyResource': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyResource,
                    request_deserializer=epoch_dot_v1_dot_regional__admin__pb2.ApplyResourceRequest.FromString,
                    response_serializer=epoch_dot_v1_dot_regional__admin__pb2.ApplyResourceResponse.SerializeToString,
            ),
            'GetResource': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResource,
                    request_deserializer=epoch_dot_v1_dot_regional__admin__pb2.GetResourceRequest.FromString,
                    response_serializer=epoch_dot_v1_dot_regional__admin__pb2.GetResourceResponse.SerializeToString,
            ),
            'ListResources': grpc.unary_unary_rpc_method_handler(
                    servicer.ListResources,
                    request_deserializer=epoch_dot_v1_dot_regional__admin__pb2.ListResourcesRequest.FromString,
                    response_serializer=epoch_dot_v1_dot_regional__admin__pb2.ListResourcesResponse.SerializeToString,
            ),
            'DeleteResource': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteResource,
                    request_deserializer=epoch_dot_v1_dot_regional__admin__pb2.DeleteResourceRequest.FromString,
                    response_serializer=epoch_dot_v1_dot_regional__admin__pb2.DeleteResourceResponse.SerializeToString,
            ),
            'BatchApplyResources': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchApplyResources,
                    request_deserializer=epoch_dot_v1_dot_regional__admin__pb2.BatchApplyResourcesRequest.FromString,
                    response_serializer=epoch_dot_v1_dot_regional__admin__pb2.BatchApplyResourcesResponse.SerializeToString,
            ),
            'GetOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOperation,
                    request_deserializer=epoch_dot_v1_dot_regional__admin__pb2.GetOperationRequest.FromString,
                    response_serializer=epoch_dot_v1_dot_regional__admin__pb2.GetOperationResponse.SerializeToString,
            ),
            'WatchResourceChanges': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchResourceChanges,
                    request_deserializer=epoch_dot_v1_dot_regional__admin__pb2.WatchResourceChangesRequest.FromString,
                    response_serializer=epoch_dot_v1_dot_regional__admin__pb2.WatchResourceChangesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'epoch.v1.RegionalAdminService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('epoch.v1.RegionalAdminService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RegionalAdminService:
    """RegionalAdmin is the versioned boundary between managed Go reconciliation
    and a regional Rust control surface. It carries desired metadata only.
    """

    @staticmethod
    def ApplyResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/epoch.v1.RegionalAdminService/ApplyResource',
            epoch_dot_v1_dot_regional__admin__pb2.ApplyResourceRequest.SerializeToString,
            epoch_dot_v1_dot_regional__admin__pb2.ApplyResourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/epoch.v1.RegionalAdminService/GetResource',
            epoch_dot_v1_dot_regional__admin__pb2.GetResourceRequest.SerializeToString,
            epoch_dot_v1_dot_regional__admin__pb2.GetResourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListResources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/epoch.v1.RegionalAdminService/ListResources',
            epoch_dot_v1_dot_regional__admin__pb2.ListResourcesRequest.SerializeToString,
            epoch_dot_v1_dot_regional__admin__pb2.ListResourcesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/epoch.v1.RegionalAdminService/DeleteResource',
            epoch_dot_v1_dot_regional__admin__pb2.DeleteResourceRequest.SerializeToString,
            epoch_dot_v1_dot_regional__admin__pb2.DeleteResourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchApplyResources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/epoch.v1.RegionalAdminService/BatchApplyResources',
            epoch_dot_v1_dot_regional__admin__pb2.BatchApplyResourcesRequest.SerializeToString,
            epoch_dot_v1_dot_regional__admin__pb2.BatchApplyResourcesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/epoch.v1.RegionalAdminService/GetOperation',
            epoch_dot_v1_dot_regional__admin__pb2.GetOperationRequest.SerializeToString,
            epoch_dot_v1_dot_regional__admin__pb2.GetOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchResourceChanges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/epoch.v1.RegionalAdminService/WatchResourceChanges',
            epoch_dot_v1_dot_regional__admin__pb2.WatchResourceChangesRequest.SerializeToString,
            epoch_dot_v1_dot_regional__admin__pb2.WatchResourceChangesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
